# Generated by Django 2.0 on 2019-01-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190112_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droppost',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
