# Generated by Django 2.0 on 2019-01-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190112_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='droppost',
            name='coffee',
        ),
        migrations.AddField(
            model_name='droppost',
            name='coffeeamount',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
