# Generated by Django 2.0 on 2019-01-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190112_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='droppost',
            name='state',
        ),
    ]
