# Generated by Django 2.0 on 2019-01-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_droppost_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droppost',
            name='coffeeamount',
            field=models.IntegerField(null=True),
        ),
    ]
