# Generated by Django 2.0 on 2019-01-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190112_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droppost',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
