# Generated by Django 2.0 on 2019-01-12 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20190112_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droppost',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
