# Generated by Django 2.0 on 2019-01-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20190112_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droppost',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
