# Generated by Django 2.0 on 2019-01-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20190112_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='droppost',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
